// Jobs Data Array
const jobs = [
  {
    id: 1,
    company: 'Google',
    Position: 'Frontend Developer',
    location: 'Tokyo',
    type: 'Full-time',
    salary: '$6000',
    description: 'Develop scalable UI using React',
  },
  {
    id: 2,
    company: 'Microsoft',
    Position: 'Backend Engineer',
    location: 'Osaka',
    type: 'Remote',
    salary: '$5500',
    description: 'Build APIs and cloud services.',
  },
  {
    id: 3,
    company: 'Amazon',
    position: 'Cloud Engineer',
    location: 'Tokyo',
    type: 'Full-time',
    salary: '$7000',
    description: 'Maintain AWS infrastructure.',
  },
  {
    id: 1,
    company: 'Google',
    Position: 'Frontend Developer',
    location: 'Tokyo',
    type: 'Full-time',
    salary: '$6000',
    description: 'Develop scalable UI using React',
  },
  {
    id: 4,
    company: 'Tesla',
    position: 'Software Engineer',
    location: 'Remote',
    type: 'Full-time',
    salary: '$6500',
    description: 'Develop automotive software systems.',
  },
  {
    id: 5,
    company: 'Meta',
    position: 'React Developer',
    location: 'Singapore',
    type: 'Remote',
    salary: '$5800',
    description: 'Create social media UI features.',
  },
  {
    id: 6,
    company: 'Samsung',
    position: 'Embedded Engineer',
    location: 'Seoul',
    type: 'Full-time',
    salary: '$6200',
    description: 'Develop IoT firmware systems.',
  },
  {
    id: 7,
    company: 'Alibaba',
    position: 'Data Analyst',
    location: 'Hangzhou',
    type: 'Full-time',
    salary: '$5000',
    description: 'Analyze business data insights.',
  },
  {
    id: 8,
    company: 'Apple',
    position: 'iOS Developer',
    location: 'California',
    type: 'Full-time',
    salary: '$7200',
    description: 'Develop iOS applications.',
  },
];
